name: foodiebox
description: A new Flutter project for a food delivery application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^1.2.0
  table_calendar: ^3.0.8

  # --- UI & Core Utility ---
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  fl_chart: ^0.69.0
  pdf: ^3.11.0
  printing: ^5.10.0

  # --- Location, Maps, and Geocoding ---
  google_maps_flutter: ^2.5.0
  geocoding: ^4.0.0
  geolocator: ^10.1.0
  google_places_flutter: ^2.0.6

  # --- Predictive Search UI ---
  flutter_typeahead: ^5.2.0

  # --- Firebase & Auth ---
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  google_place: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


# --- App Icon Configuration ---
flutter_launcher_icons:
  image_path: "assets/images/App_icons.png"
  android: true
  ios: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true

