name: foodiebox
description: A new Flutter project for a food delivery application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Core Utility ---
  cupertino_icons: ^1.0.6
  http: ^1.1.0 
  
  # --- Location, Maps, and Geocoding ---
  google_maps_flutter: ^2.5.0
  geocoding: ^4.0.0
  geolocator: ^10.1.0
  google_places_flutter: ^2.0.6

  # --- Predictive Search UI ---
  flutter_typeahead: ^5.2.0

  # --- Firebase & State Management ---
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# --- App Icon Configuration ---
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/App_icons.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/App_icons.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/App_icons.png"
  image_path: "assets/images/App_icons.png"
