name: foodiebox
description: A new Flutter project for a food delivery application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.2.0
  table_calendar: ^3.0.8
  url_launcher: ^6.3.0

  

  # --- UI & Core Utility ---
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  fl_chart: ^0.69.0
  pdf: ^3.11.0
  printing: ^5.10.0
  path_provider: ^2.0.15
  

  # --- Location, Maps, and Geocoding ---
  google_maps_flutter: ^2.14.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_places_flutter: ^2.0.6

  # --- Predictive Search UI ---
  flutter_typeahead: ^5.2.0

  # --- Firebase & Auth ---
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  google_sign_in: ^6.3.0
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  google_place: ^0.4.7
  confetti: ^0.8.0
  flutter_rating_bar: ^4.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    


# --- App Icon Configuration ---
flutter_launcher_icons:
  image_path: "assets/images/App_icons.png"
  android: true
  ios: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true